article/urls.py
from django.urls import path

from . import views

app_name = 'article'
urlpatterns = [
    # ex: /article/
    path('', views.home, name='home'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('', views.test, name='test'),
    path('<int:article_id>/', views.archives, name='archives'),
    path('search/', views.blog_search),
    # path('', views.email_send, name='email_send')
    path('email/', views.email_send),
    path('login/', views.login),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import include, path
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),
    path('article/', include('article.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
    path('confirm/', views.user_confirm)
]

article/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=50, blank=True)
    date_time = models.DateTimeField(auto_now_add=True)
    content = models.TextField(blank = True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-date_time']

login/models.py
from django.db import models

# Create your models here.

class User(models.Model):

    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    name = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=255)
    email = models.CharField(max_length=100, unique=True)
    sex = models.CharField(max_length=10, choices=gender, default="男")
    created_time = models.DateTimeField(auto_now_add=True)
    has_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        # 按创建时间反序排列,最近的优先显示
        ordering = ["-created_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"


class ConfirmString(models.Model):
    code = models.CharField(max_length=255)
    user = models.OneToOneField('User', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code

    class Meta:

        ordering = ["-created_time"]
        verbose_name = "确认码"
        verbose_name_plural = "确认码"

login/forms.py
from django import forms
from captcha.fields import CaptchaField

class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=255, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label='验证码')

class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="用户名", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=255, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=255, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    captcha = CaptchaField(label='验证码')

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from datetime import datetime
from django.http import Http404
from datetime import timezone
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
import logging
from django.contrib.auth import authenticate, login, logout

from .models import Article

# Create your views here.
logger = logging.getLogger(__name__)
# def login(request):
#     nowtime = datetime.now().strftime("%Y-%m-%d %H:%M:%S", datetime.now().localtime())
#     if request.method == 'GET':
#         return render(request, 'article/login.html', {'reason': "invalid login",'nowtime': nowtime})
#     else:
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(username=username, password=password)
#         if user is not None:
#             if user.is_active:
#                 login(request, user)
#             else:
#                 return render(request, 'article/login.html', {'reason': "disable account"})
#         else:
#             return render(request, 'article/login.html', {'reason': "invalid login"})

# def logout_view(request):
#     logout(request)
#     return render(request, 'article/login.html', {'reason': "logout success"})

def home(request):
    posts = Article.objects.all()
    paginator = Paginator(posts, 2)
    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.paginator(paginator.num_pages)
    logger.debug("paginator has executed!")
    return render(request, 'article/home.html', {'post_list': post_list})

def detail(request, article_id):
    post = Article.objects.get(pk=article_id)
    return render(request, 'article/detail.html', {'post': post})

def archives(request, article_id) :
    try:
        post_list = Article.objects.get(pk=article_id)
    except Article.DoesNotExist:
        raise Http404
    return render(request, 'article/archives.html', {'post_list': post_list, 'error': False})

def blog_search(request):
    if 's' in request.GET:
        s = request.GET['s']
        if not s:
            logger.info("s is not exist!")
            return render(request,'article/home.html')
        else:
            post_list = Article.objects.filter(title__icontains=s)
            if len(post_list) == 0 :
                return render(request,'article/archives.html', {'post_list' : post_list,
                                                    'error' : True})
            else:
                return render(request,'article/archives.html', {'post_list' : post_list,
                                                    'error' : False})
    return redirect('/')

def email_send(request):
    send_mail('Subject here', 'Here is the message.', 'campus@xjgreat.com',
              ['data_monitor_services@xjgreat.com'], fail_silently=False)
    logger.debug("email has send!")
    return render(request, 'article/email_send.html')

def test(request):
    return render(request, 'article/test.html', {'current_time': datetime.now()})

login/views.py
from django.shortcuts import render, redirect
from login.models import User, ConfirmString
from .forms import UserForm, RegisterForm
import hashlib
import datetime
import pytz
from django.conf import settings

# Create your views here.
utc=pytz.UTC

def hash_code(s, salt='my_blog'):# 加点盐
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()

def make_confirm_string(user):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_code(user.name, now)
    ConfirmString.objects.create(code=code, user=user)
    return code

def send_email(email, code):

    from django.core.mail import EmailMultiAlternatives

    subject = '来自my_blog的注册确认邮件'

    text_content = '''感谢注册my_blog，这里专注于Python和Django技术的分享！\
                    如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！'''

    html_content = '''
                    <p>感谢注册<a href="http://{}/confirm/?code={}" target=blank>my_blog</a>，\
                    这里专注于Python和Django技术的分享！</p>
                    <p>请点击站点链接完成注册确认！</p>
                    <p>此链接有效期为{}天！</p>
                    '''.format('127.0.0.1:8000', code, settings.CONFIRM_DAYS)

    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()

def index(request):
    pass
    return render(request, 'login/index.html')

def login(request):
    if request.session.get('is_login', None):
        return redirect("/index/")
    if request.method == "POST":
        login_form = UserForm(request.POST)
        message = "请检查填写的内容！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                user = User.objects.get(name=username)
                if not user.has_confirmed:
                    message = "该用户还未通过邮件确认！"
                    return render(request, 'login/login.html', locals())
                if user.password == hash_code(password):
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return redirect('/index/')
                else:
                    message = "密码不正确！"
            except:
                message = "用户不存在！"
        return render(request, 'login/login.html', locals())

    login_form = UserForm()
    return render(request, 'login/login.html', locals())

def register(request):
    if request.session.get('is_login', None):
        # 登录状态不允许注册。你可以修改这条原则！
        return redirect("/index/")
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():  # 获取数据
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = User.objects.filter(name=username)
                if same_name_user:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return render(request, 'login/register.html', locals())
                same_email_user = User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'login/register.html', locals())

                # 当一切都OK的情况下，创建新用户

                new_user = User.objects.create()
                new_user.name = username
                new_user.password = hash_code(password1)  # 使用加密密码
                new_user.email = email
                new_user.sex = sex
                new_user.save()

                code = make_confirm_string(new_user)
                send_email(email, code)

            message = '请前往注册邮箱，进行邮件确认！'
            return render(request, 'login/confirm.html', locals())  # 跳转到等待邮件确认页面。
    register_form = RegisterForm()
    return render(request, 'login/register.html', locals())

def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/index/")
    request.session.flush()
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/index/")

def user_confirm(request):
    code = request.GET.get('code', None)
    message = ''
    try:
        confirm = ConfirmString.objects.get(code=code)
    except:
        message = '无效的确认请求!'
        return render(request, 'login/confirm.html', locals())

    c_time = confirm.created_time
    now = utc.localize(datetime.datetime.now())
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = '您的邮件已经过期！请重新注册!'
        return render(request, 'login/confirm.html', locals())
    else:
        confirm.user.has_confirmed = True
        confirm.user.save()
        confirm.delete()
        message = '感谢确认，请使用账户登录！'
        return render(request, 'login/confirm.html', locals())

article/templates/article/archives.html
{% extends "article/base.html" %}

{% block content %}
<div class="posts">
    {% if error %}
        <h2 class="post-title">没有相关文章题目</h2>
    {% else %}
        {% for post in post_list %}
            <section class="post">
                <header class="post-header">
                    <h2 class="post-title"><a href="{% url 'article:detail' post.id %}">{{ post.title }}</a></h2>

                    <p class="post-meta">
                        Time: <a class="post-author" href="#">{{ post.date_time |date:"Y /m /d" }}</a>
                    </p>
                </header>
            </section>
        {% endfor %}
    {% endif %}
</div><!-- /.blog-post -->
{% endblock %}

article/templates/article/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A layout example that shows off a blog page with a list of posts.">

    <title>Andrew Liu Blog</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/blog.css">

</head>
<body>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title"><a href="#">Andrew Liu Blog</a></h1>
            <h2 class="brand-tagline">雪忆 - Snow Memory</h2>
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="button-success pure-button" href="{% url 'article:home' %}">主页</a>
                    </li>
{#                    <li class="nav-item">#}
{#                        <a class="button-success pure-button" href="{% url 'article:archives' 1 %}">归档</a>#}
{#                    </li>#}
                    <li class="nav-item">
                        <a class="pure-button" href="https://github.com/teccm1994/django_blog" target="_blank">Github</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-error pure-button" href="http://www.sina.com.cn/" target="_blank">Weibo</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button" href="#">专题</a>
                    </li>
                    <li class="nav-item">
{#                        <a class="pure-button" href="{% url 'article:email' %}">Email</a>#}
                        <a class="pure-button" href="http://127.0.0.1:8000/article/email">Email</a>
                    </li>
                    <form class="pure-form" action="/article/search/" method="get">
                    <input class="pure-input-3-3" type="text" name="s" placeholder="search">
                    </form>
{#                    <li class="nav-item">#}
{#                        <a class="button-success pure-button" href="#">About Me</a>#}
{#                    </li>#}
                </ul>
            </nav>
        </div>
    </div>


    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal pure-menu-open">
                    <ul>
                        <li><a href="http://andrewliu.tk/about/">About Me</a></li>
                        <li><a href="http://twitter.com/yuilibrary/">Twitter</a></li>
                        <li><a href="http://github.com/yahoo/pure/">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

article/templates/article/detail.html
{% extends "article/base.html" %}

{% block content %}
<div class="posts">
        <section class="post">
            <header class="post-header">
                <h2 class="post-title">{{ post.title }}</h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time|date:"Y /m /d"}}</a> <a class="post-category post-category-js" href="#">{{ post.category }}</a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content|truncatewords_html:10 }}
                    </p>
                </div>
        </section>
</div><!-- /.blog-post -->
{% endblock %}

article/templates/article/email_send.html
<p><<<a href="{% url 'article:home' %}">返回主页</a></p>
<h2>邮件发送成功!</h2>

article/templates/article/home.html
{% extends "article/base.html" %}

{% block content %}
    <div class="posts">
        {% for post in post_list %}
            <section class="post">
                <header class="post-header">
                    <h2 class="post-title"><a href="{% url 'article:detail' post.id %}">{{ post.title }}</a></h2>

                    <p class="post-meta">
                        Time: <a class="post-author" href="#">{{ post.date_time }}</a> <a
                            class="post-category post-category-js" href="#">{{ post.category }}</a>
                    </p>
                </header>

                <div class="post-description">
                    <p>
                        {{ post.content|truncatewords_html:5 }}
                    </p>
                </div>
                <a class="pure-button" href="{% url 'article:detail' post.id %}">Read More >>> </a>
            </section>
        {% endfor %}

        {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
            <div>
                <ul class="pager">
                    {% if post_list.has_previous %}
                        <li><a href="?page={{ post_list.previous_page_number }}">上一页</a></li>
                    {% endif %}

                    {% if post_list.has_next %}
                        <li><a href="?page={{ post_list.next_page_number }}">下一页</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </div><!-- /.blog-post -->
{% endblock %}

article/templates/article/login.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Login</title>
</head>
<body>
    <div class="admin-ht" style="background: #eeeeee">
        <div class="adminBord">
            <h1>雪忆博客</h1>
        <h4>{{ nowtime }}</h4>
            <form class="pure-form" action="/article/login/" method="post">
                <input class="pure-input-3-3" type="text" name="username" placeholder="用户名">
                <input class="pure-input-3-3" type="text" name="password" placeholder="密码">
                <input type="submit" value="login" >
            </form>
        </div>
    </div>
</body>
</html>

article/templates/article/test.html
<!DOCTYPE html>
<html>
    <head>
        <title>Just test template</title>
        <style>
            body {
               background-color: red;
            }
            em {
                color: LightSeaGreen;
            }
        </style>
    </head>
    <body>
        <h1>Hello World!</h1>
        <strong>{{ current_time }}</strong>
    </body>
</html>